name: Deploy to Debian 12 VPS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.VPS_PRIVATE_KEY }}

    - name: Add VPS to known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

    - name: Execute deployment
      run: |
        ssh -o StrictHostKeyChecking=no \
            -p ${{ secrets.SSH_PORT }} \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
        # Configurar ambiente
        mkdir -p /home/deploy
        cd /home/deploy
        
        # Clone ou atualize o repositório
        if [ ! -d "site" ]; then
          git clone https://github.com/Kuarion/site.git site
          cd site
        else
          cd site
          git pull origin main
        fi
        
        # Build e execução do Docker (Debian 12 específico)
        docker build -t kuarion-app .
        
        # Parar e remover container existente
        docker stop kuarion-container || true
        docker rm kuarion-container || true
        
        # Rodar novo container com reinício automático
        docker run -d \
          --restart unless-stopped \
          -p 80:8080 \
          --name kuarion-container \
          kuarion-app
        
        # Limpar imagens não utilizadas
        docker image prune -af
        EOF
